/**
 * Utilities for storing the vault master key locally on the device.
 * The master key stays client-side; only encrypted derivatives are uploaded.
 */

const STORAGE_KEY = "vaultMasterKey";

/**
 * Reads the base64-encoded master key from localStorage.
 * @returns {string|null} Base64 master key or null when missing.
 */
export function getLocalMasterKey() {
  if (typeof window === "undefined") return null;
  return window.localStorage.getItem(STORAGE_KEY);
}

/**
 * Persists the base64-encoded master key to localStorage.
 * @param {string} masterKey - Base64 master key generated by generateMasterKey().
 */
export function setLocalMasterKey(masterKey) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, masterKey);
}

/**
 * Removes the stored master key (e.g., when user logs out or clears cache).
 */
export function clearLocalMasterKey() {
  if (typeof window === "undefined") return;
  window.localStorage.removeItem(STORAGE_KEY);
}
